### ISSUE TITLE
Queue declare problem

### ISSUE THREAD

**Issue by yak0** [sboily/asterisk-stasis-amqp#10]
How we can handle queue declaring?  Queues names are dynamic like stasis.channel.1543415469.8
The module does not declare a queue, mandatory parameter is false and messages drop when queue did not declared

**Comment by sboily** [comment]
Hello,

I'm not sure to understand your problem. stasis.channel.1543415469.8 is not the queue name this is the routing key. Why do you need a static queue name?

**Comment by yak0** [comment]
oh really! sorry I totally misunderstand. By the way this module is very useful thanks for your interest

**Comment by sboily** [comment]
No problem, you're welcome.
