### ISSUE TITLE
had to reload the module if you reconnect to the websocket

### ISSUE THREAD

**Issue by nicolasturcksin** [sboily/asterisk-stasis-amqp#11]
Hi,

First thanks for this module it's very useful great job ! But I have a question, Maybe I misunderstood the module configuration, but you had to be connected with you application on asterisk to received events, Should be possible to manage the connection of your user with the res_stasis_amqp module ?

Also when I reconnect the application, you had to reload the module res_stasis_amqp to receive events again, if the module manage the connection this problem will disappear.

Thanks.

**Comment by sboily** [comment]
Hello, please check the fork on wazo-platform. This code is not up to date. I'm note sure to understand your question. This modules send all stasis information in rabbitmq. But check the latest branch on our fork wazo-platform.
